### ISSUE TITLE
Are trusted tasks only trusted one month in the future?

### ISSUE THREAD

**Issue by ralphbean** [enterprise-contract/ec-policies#1048]
I was messing around with some new policy, and I stumbled on something I didn't understand:

```
❯ oras pull quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest                                                             
✓ Skipped     application/vnd.unknown.config.v1+json                                                                                     
  └─ sha256:7ae565083efdd22c021ed9b27519f387b46483c5006e19ff8a5745fd7405eb28
✓ Pulled      data/data/trusted_tekton_tasks.yml                                                                                         
  └─ sha256:55d522ff759626695f74e3149aaabfb09cd15a9fcae545bccbe12d7de3d7493e
✓ Pulled      application/vnd.oci.image.manifest.v1+json                                                                                 
  └─ sha256:75b16a2f2fa5598e76b490ea21bf7c03bc9525a91fcc32c5ca43217eb4923943
Skipped pulling layers without file name in "org.opencontainers.image.title"
Use 'oras copy quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest --to-oci-layout <layout-dir>' to pull all layers.

❯ cat data/data/trusted_tekton_tasks.yml | yq '.trusted_tasks."oci://quay.io/konflux-ci/tekton-catalog/task-oci-copy:0.1"[].effective_on'
2024-07-22T00:00:00Z

❯ date +%Y-%m-%d                                                                                                                         
2024-06-21                                                                                                                                        
```

The date is currently June 21.

I just merged a new task in build-definitions. The digest of its bundle already appears in the acceptable bundles oci image - awesome!

But, the `effective_on` date is set to one month from now -- july 22nd. Does that mean the task will _not_ be trusted for another month and only become trusted after that date?

If so, is that desired behavior?

**Comment by ralphbean** [comment]
Well, on reading the doc in `track_bundle.go`, I see now that the effective_on date doesn't mean that the task becomes trusted on that date, but rather that "the Tekton Bundle usage should be updated [by that date]".

> Any entry with an effective_on date in the future, and the entry with
> the most recent effective_on date *not* in the future are considered
> acceptable.

That makes sense now.

**Comment by ralphbean** [comment]
Maybe instead of "effective_on" it should be required_on or required_by. That's the date at which point prior bundles are no longer trusted.

Then again, maybe that's splitting hairs. It makes sense now.

**Comment by zregvart** [comment]
There are also [docs for this](https://enterprisecontract.dev/docs/ec-policies/trusted_tasks.html)

**Comment by simonbaird** [comment]
I recall one discussion where we said the `effective_on` is vestigial and can be removed in the near future. IIUC the current logic is that if it's present then it's effective.
