### ISSUE TITLE
Examine `konflux:container:is_builder_image:for_stage` formulation components properties

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1082]
Currently we examine `formulation.components[].properties.name == "konflux:container:is_base_image"` values that hold the base image of the image, we also need to look at the formulation properties named `konflux:container:is_builder_image:for_stage` (if any), to examine all images that were used to build the image.

These might be new rules, or addition to existing rules in [base_image_registries](https://github.com/enterprise-contract/ec-policies/blob/main/policy/release/base_image_registries.rego).

**Comment by lcarva** [comment]
Isn't that what this does? https://github.com/enterprise-contract/ec-policies/blob/540adf985ae1432fc16129a7bc5676222da9d1c3/policy/release/base_image_registries.rego#L122-L134

**Comment by zregvart** [comment]
Missed that, let's close this.
