### ISSUE TITLE
Stop depending on `BASE_IMAGES_DIGESTS` TaskRun result

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1155]
The `BASE_IMAGES_DIGESTS` TaskRun result will be [deprecated](https://issues.redhat.com/browse/STONEBLD-2747) and [removed](https://github.com/konflux-ci/build-definitions/pull/1471).

We have the [`base_image_registries.base_image_info_found` rule](https://github.com/enterprise-contract/ec-policies/blob/d3fae91e850af94dd3d4cc7b8497b21c4afa2227/policy/release/base_image_registries.rego#L42-L71) that checks that the `BASE_IMAGES_DIGESTS` TaskRun result is provided, we most likely need to remove [that part of the](https://github.com/enterprise-contract/ec-policies/blob/d3fae91e850af94dd3d4cc7b8497b21c4afa2227/policy/release/base_image_registries.rego#L67) rule and adjust the documentation. As well as [fetching the base image](https://github.com/enterprise-contract/ec-policies/blob/d3fae91e850af94dd3d4cc7b8497b21c4afa2227/policy/release/base_image_registries.rego#L99-L103) information via that result.

**Comment by lcarva** [comment]
We should definitely do that for clean up purposes. :+1: 

I just want to clarify that all the rules in that package should handle the case where that result is not specified. `base_image_registries.base_image_info_found` for example will only emit a violation if the result is not found **and** no sboms were also found.
