### ISSUE TITLE
Test failure when offline

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1185]
A test seems to be failing when run without internet connection:

```
policy/release/sbom_cyclonedx_test.rego:
data.policy.release.sbom_cyclonedx_test.test_not_valid: FAIL (5.320726ms)

  Assert equal failure:
    Left value:  {{"code": "sbom_cyclonedx.valid", "msg": "CycloneDX SBOM at index 0 is not valid: components: Invalid type. Expected: array, given: string"}}
    Right value: set()
````

**Comment by lcarva** [comment]
Hmm from the debugger it _looks_ like this happening in `json.match_schema` :confused:

**Comment by lcarva** [comment]
The `$id` attribute is apparently what triggers this.

```json
{                                                                                              
  "$schema": "http://json-schema.org/draft-07/schema#",                                        
  "$id": "http://cyclonedx.org/schema/bom-1.5.schema.json",                                    
  "type": "object",                                                                            
  "title": "CycloneDX Software Bill of Materials Standard",                                    
  "$comment" : "CycloneDX JSON schema is published under the terms of the Apache License 2.0.",
  "required": [                                                                                
    "bomFormat",                                                                               
    "specVersion"                                                                              
  ],                                                                                           
...
```

**Comment by lcarva** [comment]
It looks like there are two `$ref` values in the CycloneDX schema that causes an HTTP request:

https://github.com/enterprise-contract/ec-policies/blob/dfad943e1ca1972b54dd1f08a7a93a1f894469ce/policy/release/sbom_cyclonedx_schema.rego#L728

https://github.com/enterprise-contract/ec-policies/blob/dfad943e1ca1972b54dd1f08a7a93a1f894469ce/policy/release/sbom_cyclonedx_schema.rego#L3505

If  delete those lines, no network connection is needed. Incidentally, this also makes the call sooo much faster, from `391.630462ms` to `3.982811ms`.

This happens [here](https://github.com/open-policy-agent/opa/blob/fefd1ca6fef4034cdfbd8f35f1d98b01dd2cc503/internal/gojsonschema/jsonLoader.go#L212) when the JSON schema is loaded.

**Comment by lcarva** [comment]
We can bundle it to make avoid the network call: https://json-schema.org/understanding-json-schema/structuring#bundling

**Comment by zregvart** [comment]
> If delete those lines, no network connection is needed. Incidentally, this also makes the call sooo much faster, from `391.630462ms` to `3.982811ms`.

:scream_cat:
