### ISSUE TITLE
Drop support for fetching SBOM data from the image under test

### ISSUE THREAD

**Issue by zregvart** [enterprise-contract/ec-policies#1197]
Version 0.1 of the buildah Task is out of support (expires) on [2024-11-13](https://github.com/konflux-ci/build-definitions/blob/31180b4b4c06e971dcaaac34ec2cfa62355469d9/task/buildah/0.1/buildah.yaml#L10), from that onward we do not need to look for the SBOM files in the image under test. That is, we can remove `*_from_image` fallbacks in `lib.sbom`.

**Comment by lcarva** [comment]
This was done in https://github.com/enterprise-contract/ec-policies/pull/1229.
