### ISSUE TITLE
Support test tasks (producing TEST_OUTPUT results) that should not produce EC violations on test failures

### ISSUE THREAD

**Issue by simonbaird** [enterprise-contract/ec-policies#782]
## Background

The motivation for this is for RHTAP's `sast-snyk-check` task.

The policy for this task aiui is that:
* It must be present in the pipeline
* It must not be skipped
* It must produce a TEST_OUTPUT task result with the usual format
* However, unlike the current behavior, and the expected behavior for other tasks producing a TEST_OUTPUT task result, a non-zero failure count should not produce an EC violation.
* (This requirement was less clear, but) I think producing an EC warning would be the reasonable thing to do in the case where sast-snyk-check reported some failures in its TEST_OUTPUT result.

## Requirement

So the requirement is for EC to be able to enforce the policy as stated above.

## Implementation:

How to do this is open, but perhaps something like this would work:

* Introduce a new piece of rule data with a suitable name like `warn_only_for_test_failures` that contains a list of task names.
* The default for this can be an empty list, (but perhaps in the RH specific RHTAP data config it will include a single value, `sast-snyk-check`).
* Modify the existing rego rule `test.required_tests_passed` so it doesn't produce a violation for tasks in that list.
* Introduce a new rego rule that examines only tasks in that list. It should produce a warning if there are failures present in TEST_OUTPUT.

**Comment by simonbaird** [comment]
Enforcing that the task is present and not skipped is already done IIUC, since the task is present in the required_tasks list.

**Comment by lcarva** [comment]
This was fixed in https://github.com/enterprise-contract/ec-policies/pull/793
