### ISSUE TITLE
Move beta.packages to release.sbom_cyclonedx

### ISSUE THREAD

**Issue by lcarva** [enterprise-contract/ec-policies#816]
In #732, new policy rules were added that use the newly added `ec.purl.parse` custom rego function. To avoid issues with older versions of the ec-cli that do not provide the function, they were added to a new namespace, `policy/beta`, instead of the usual `policy/release`. 

This issue is about moving those policy rules to `policy/release`, likely under the `sbom_cyclonedx` package.

Let's aim for doing this right after January 1st as that should be sufficient time to allow clients to update.

**Acceptance Criteria**

* The policy rules from `beta.packages` are moved under the `release` namespace.

**Comment by zregvart** [comment]
The `ec.purl.parse` needs at least version [2269](https://github.com/enterprise-contract/ec-cli/pull/1173/commits/5211e454cb0f59d6eb1db99b794559c051234c9f) in the last 7 days the oldest version was 2340 and in the last 30 days the oldest version was 2286. I think it is now safe to do this.
